Taskify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Taskify_auth.urls')),
    path('api/', include('Taskify_api.urls')),
    path('', include('Taskify_main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Taskify_main/urls.py
from django.urls import path, include
from Taskify_main.views.projects import ProjectListView, ProjectManageView

app_name = 'main'
urlpatterns_projects = [
    path("", ProjectListView.as_view(), name="project_list"),
    path("create/", ProjectManageView.as_view(method_name="manage"), name="project_add"),
    path("edit/<str:pk>/", ProjectManageView.as_view(method_name="manage"), name="project_edit")
]


urlpatterns = [
    path("projects/", include(urlpatterns_projects)),
]

Taskify_main/models.py
from django.db import models

from Taskify.utils import BaseContent
from Taskify_auth.models import User

# Create your models here.
STATUS_CHOICES = (
    ('no_progress', 'No Progress'),
    ('in_progress', 'In Progress'),
    ('completed', 'Completed')
)
PRIORITY_CHOICES = (
    ('', 'None'),
    ('low', 'Low'),
    ('medium', 'Medium'),
    ('high', 'High')
)


class SystemVariables(BaseContent):
    code = models.CharField(max_length=100, unique=True)
    title = models.CharField("Title", max_length=100)
    value = models.TextField("Value", max_length=1000)

    class Meta:
        unique_together = ["code", "title", "value"]

    def __str__(self):
        return f"{self.title}: {self.value}"


class Projects(BaseContent):
    name = models.CharField("Project Name", max_length=100)
    description = models.TextField("description", blank=True, null=True)
    secondary_avatar = models.FileField(upload_to="avatar", null=True)
    primary_avatar = models.FileField("Avatar", upload_to="avatar", blank=True, null=True,
        help_text="Recommended thumbnail size 800x400 (px)."
    )
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def get_avatar_url(self):
        if self.primary_avatar:
            return self.primary_avatar.url
        return self.secondary_avatar.url


class TasksLists(BaseContent):
    name = models.CharField("Title", max_length=255)
    description = models.TextField("Description", null=True, blank=True)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE, null=True,related_name='task_list')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)


class Task(BaseContent):
    task_list = models.ForeignKey(TasksLists, on_delete=models.CASCADE, null=True, related_name='tasks')
    name = models.CharField("Title", max_length=255)
    description = models.TextField("Description", null=True, blank=True)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='no_progress')
    priority = models.CharField(max_length=100, choices=PRIORITY_CHOICES, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_tasks', null=True)


class TaskAttachments(BaseContent):
    task = models.ForeignKey(Task,on_delete=models.CASCADE)
    files = models.FileField(upload_to='tasks')

Taskify_main/forms.py
from django import forms
from django.core.files.storage import default_storage
from django.core.files import File
from io import BytesIO
from Taskify_main.models import Projects
from Taskify.utils import AvatarGenerator

import os
import requests


class ProjectManageForm(forms.ModelForm):
    class Meta:
        model = Projects
        fields = ["name", "primary_avatar", "description"]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(ProjectManageForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def save(self, commit=True, created_by=None):
        instance = super().save(commit=False)
        instance.created_by = self.request.user
        if commit:
            AVG = AvatarGenerator(title=instance.name)
            file = AVG.generate()
            absolute_url = default_storage.url(file)
            image_url = self.request.build_absolute_uri(absolute_url)

            resp = requests.get(image_url)
            fp = BytesIO()
            fp.write(resp.content)
            filename = os.path.basename(image_url)

            instance.secondary_avatar.save(filename, File(fp))
            instance.save()
            self.save_m2m()

        return instance

Taskify_main/views/projects.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView

from Taskify_main.models import Projects
from Taskify_main.forms import ProjectManageForm
from Taskify.utils import ManageBaseView, get_object_or_none
from Taskify.constants import CREATE_INSTANCE


class ProjectListView(TemplateView):
    template_name = "project_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Projects.objects.all()
        return context


class ProjectManageView(View, ManageBaseView):

    def manage(self, request, *args, **kwargs):
        instance = get_object_or_none(Projects, id=kwargs.get("pk"))
        form = ProjectManageForm(instance=instance, request=request)
        if request.method == "POST":
            form = ProjectManageForm(request.POST, request.FILES, instance=instance, request=request)
            if form.is_valid():
                form.save()
                messages.success(request, CREATE_INSTANCE)
                return redirect("main:project_list")
        return render(request, "project_manage.html", locals())

Taskify_main/templates/project_grid.html
{% for project in projects %}
<div class="col-md-6 col-xxl-3">
    <!-- project card -->
    <div class="card d-block">
        <!-- project-thumbnail -->
        <img class="card-img-top" src="{{project.get_avatar_url}}" alt="project image cap">

        <div class="card-img-overlay">
            <div class="badge bg-success p-1">Finished</div>
        </div>

        <div class="card-body position-relative">

            <div class="dropdown card-widgets">
                        <a href="#" class="dropdown-toggle arrow-none" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="dripicons-dots-3"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <!-- item-->
                            <a href="{% url 'main:project_edit' project.id %}" class="dropdown-item"><i class="mdi mdi-pencil me-1"></i>Edit</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item"><i class="mdi mdi-delete me-1"></i>Delete</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item"><i class="mdi mdi-email-outline me-1"></i>Invite</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item"><i class="mdi mdi-exit-to-app me-1"></i>Leave</a>
                        </div>
                    </div>

            <!-- project title-->
            <h4 class="mt-0">
                <a href="apps-projects-details.html" class="text-title">{{project}}</a>
            </h4>

            <!-- project detail-->
            <p class="mb-3">
                <span class="pe-2 text-nowrap">
                    <i class="mdi mdi-format-list-bulleted-type"></i>
                    <b>11</b> Tasks
                </span>
                <span class="text-nowrap">
                    <i class="mdi mdi-comment-multiple-outline"></i>
                    <b>254</b> Comments
                </span>
            </p>
            <div class="mb-3" id="tooltip-container5">
                <a href="javascript:void(0);" data-bs-container="#tooltip-container5" data-bs-toggle="tooltip" data-bs-placement="top" title="" class="d-inline-block" data-bs-original-title="Mat Helme">
                    <img src="assets/images/users/avatar-10.jpg" class="rounded-circle avatar-xs" alt="friend">
                </a>

                <a href="javascript:void(0);" data-bs-container="#tooltip-container5" data-bs-toggle="tooltip" data-bs-placement="top" title="" class="d-inline-block" data-bs-original-title="Michael Zenaty">
                    <img src="assets/images/users/avatar-5.jpg" class="rounded-circle avatar-xs" alt="friend">
                </a>

                <a href="javascript:void(0);" data-bs-container="#tooltip-container5" data-bs-toggle="tooltip" data-bs-placement="top" title="" class="d-inline-block" data-bs-original-title="James Anderson">
                    <img src="assets/images/users/avatar-7.jpg" class="rounded-circle avatar-xs" alt="friend">
                </a>
                <a href="javascript:void(0);" class="d-inline-block text-muted fw-bold ms-2">
                    +2 more
                </a>
            </div>

            <!-- project progress-->
            <p class="mb-2 fw-bold">Progress <span class="float-end">100%</span></p>
            <div class="progress progress-sm">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                </div><!-- /.progress-bar -->
            </div><!-- /.progress -->
        </div> <!-- end card-body-->
    </div>
    <!-- end card-->
</div>
{% endfor %}

Taskify_main/templates/project_list.html
{% extends "dashboard.html" %}

{% block content %}
<div class="container-fluid">

    {% include "root_links.html" %}

    <div class="row mb-2">
        <div class="col-sm-4">
            <a href="{% url 'main:project_add' %}" class="btn btn-danger rounded-pill mb-3">
                <i class="mdi mdi-plus"></i> Create Project
            </a>
        </div>
        <div class="col-sm-8">
            <div class="text-sm-end">
                <div class="btn-group mb-3">
                    <button type="button" class="btn btn-primary">All</button>
                </div>
                <div class="btn-group mb-3 ms-1">
                    <button type="button" class="btn btn-light">Ongoing</button>
                    <button type="button" class="btn btn-light">Finished</button>
                </div>
                <div class="btn-group mb-3 ms-2 d-none d-sm-inline-block">
                    <button type="button" class="btn btn-secondary"><i class="dripicons-view-apps"></i></button>
                </div>
                <div class="btn-group mb-3 d-none d-sm-inline-block">
                    <button type="button" class="btn btn-link text-muted"><i class="dripicons-checklist"></i></button>
                </div>
            </div>
        </div><!-- end col-->
    </div>
    <!-- end row-->

    <div class="row">
        {% if object_list %}
            {% include "project_grid.html" with projects=object_list %}
        {% else %}
            <h1>No Data Found</h1>
        {% endif %}
    </div>
    <!-- end row-->

</div>
{% endblock content %}

Taskify_main/templates/project_manage.html
{% extends "dashboard.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">

    {% include "root_links.html" %}

    <div class="row">
        <div class="col-12">
            <form class="card" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                    {% include "basic_form.html" with form=form %}
                </div>
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-primary" id="formSubmit">Submit</button>
                    <a href="" class="btn btn-light">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js_plug %}
<script src="{% static 'user/assets' %}/js/vendor/dropzone.min.js"></script>
<script src="{% static 'user/assets' %}/js/ui/component.fileupload.js"></script>
{% endblock %}
{% block extra_js %}
<script>
    $(document).on("submit", function(event){
        event.preventDefault();
        swal({
            title: "Are you sure?",
            text: "Do you want to process!",
            type: "warning",
            showCancelButton: true,
            confirmButtonClass: "btn-primary",
            confirmButtonText: "Submit",
        }, (isConfirm)=>{
            if (!isConfirm) return;
            $(this).off('submit');
            $("#formSubmit").click();
        })
    })
</script>
{% endblock extra_js %}